name: Build and Deploy

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.yourserver.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: path/to/your/server/directory
        local-dir: docs/_build/html
